name: Build and Publish Plugins

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Plugins
        run: ./gradlew makePlugins

      - name: Copy CS3 plugins to build directory
        run: |
          find . -type f -name "*.cs3" -exec cp {} ./build/ \;

      - name: Deploy to builds branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: builds
          publish_dir: ./build
